[project]
name = "projekt-idub"
version = "0.1.0"
description = "idub_2026"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "h5py>=3.16.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "pytest>=9.1.1",
    "qutip>=5.3.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu132" }
torchvision = { index = "pytorch-cu132" }
